name: Create Release Branch

on:
  push:
    tags:
      - "*"

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup git
        run: |
          git config user.name 'Nazmuz Pranto'
          git config user.email 'npranto4@gmail.com'

      - name: Create branch from tag
        run: |
          tag=$(echo ${GITHUB_REF#refs/tags/})
          branch="release/$tag"
          git checkout -b $branch
          git push -u origin $branch
