name: Deploy Tag to Bucket

on:
  workflow_dispatch:
    inputs:
      bucket:
        description: "Bucket to use for custom deploy?"
        required: true
        default: "bucket-1"
        options: |
          [
            {
              "label": "Bucket 1",
              "value": "bucket-1",
              "selected": true
            },
            {
              "label": "Bucket 2",
              "value": "bucket-2"
            },
            {
              "label": "Bucket 3",
              "value": "bucket-3"
            },
            {
              "label": "Bucket 4",
              "value": "bucket-4"
            },
            {
              "label": "Bucket 5",
              "value": "bucket-5"
            }
          ]
      tag:
        description: "Tag to deploy to bucket?"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout tag on bucket branch
        run: |
          TAG=${{ inputs.tag }}
          BUCKET_BRANCH=${{ inputs.bucket }}
          git checkout main
          git fetch --tags
          git push --delete origin $BUCKET_BRANCH || true
          git checkout $TAG
          git checkout -b $BUCKET_BRANCH
          git push --set-upstream origin $BUCKET_BRANCH
