name: Generate Changelog

on:
  pull_request:
    branches:
      - main

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Determine version type
        run: |
          PR_TITLE=$(echo "${{ github.event.pull_request.title }}" | tr '[:upper:]' '[:lower:]')
          if [[ $PR_TITLE == *"[major]"* ]]; then
            VERSION_TYPE="major"
          elif [[ $PR_TITLE == *"[minor]"* ]]; then
            VERSION_TYPE="minor"
          else
            VERSION_TYPE="patch"
          fi
      - name: Generate Changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx conventional-changelog-cli -p angular -i CHANGELOG.md -s -r 0 -t "v" -n "$VERSION_TYPE"
      - name: Commit Changelog
        run: |
          git config --global user.name "nsp-playground"
          git config --global user.email "npranto4@gmail.com"
          git add CHANGELOG.md
          git commit -m "docs: update changelog [skip ci]"
          git push
