name: "Manual: Bump Version + Create Tag"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Select semantic version increment?"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump-version-create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup git
        run: |
          git config user.name 'Nazmuz Pranto'
          git config user.email 'npranto4@gmail.com'

      - name: Bump version
        run: npm version ${{ github.event.inputs.version }}

      - name: Push latest version
        run: git push origin main --follow-tags
